version: '2'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2022.11fv5
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
    volumes:
       - './pihole_config/etc-pihole/:/etc/pihole/'
       - './pihole_config/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: always