version: '2'
services:
 unifi-controller:
   container_name: unifi-controller
   image: linuxserver/unifi-controller:7.2.95
   restart: always
   volumes:
     - './unifi_config:/config'
   ports:
     - '3478:3478/udp'
     - '10001:10001/udp'
     - '6789:6789/tcp'
     - '8080:8080/tcp'
     - '8880:8880/tcp'
     - '8443:8443/tcp'
     - '8843:8843/tcp'
   environment:
     - PGID=0
     - PUID=0
     - TZ=America/New_York
   labels:
     - 'unifi-controller'